apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-v4yvib
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v4yvib
  namespace: my-nginx-v4yvib
  labels:
    name: nginx-v4yvib
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-v4yvib
  template:
    metadata:
      namespace: my-nginx-v4yvib
      labels:
        name: nginx-v4yvib
    spec:
      containers:
      - name: nginx-v4yvib
        image: nginx
        ports:
        - containerPort: 80

